import { Service, DashboardData, Incident, Alert, SLAStatus, Report, Metric } from '../types';

export const demoUser = {
  id: 'demo-admin-id',
  name: 'System Admin',
  email: 'admin@slapulse.io',
  role: 'ADMIN',
  createdAt: new Date().toISOString(),
};

export const demoServices: Service[] = [
  {
    id: 'srv-1',
    name: 'Stripe Payment Gateway',
    description: 'Global online payment processing & subscription billing API',
    url: 'https://api.stripe.com/v1/charges',
    environment: 'Production',
    region: 'us-east-1',
    status: 'healthy',
    slaTarget: 99.99,
    latencyThreshold: 250,
    pageLoadThreshold: 1.2,
    errorRateThreshold: 0.05,
    monitoringEnabled: true,
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    latestMetric: {
      id: 'm-1',
      serviceId: 'srv-1',
      latency: 185,
      pageLoadTime: 0.85,
      uptime: 100,
      errorRate: 0.01,
      timestamp: new Date().toISOString(),
    },
    slaConfig: {
      id: 'sla-1',
      serviceId: 'srv-1',
      availabilitySLA: 99.99,
      responseTimeSLA: 250,
      pageLoadSLA: 1.2,
      errorRateSLA: 0.05,
    },
  },
  {
    id: 'srv-2',
    name: 'AWS S3 Object Storage',
    description: 'High-durability cloud file storage & asset delivery',
    url: 'https://s3.us-east-1.amazonaws.com',
    environment: 'Production',
    region: 'us-east-1',
    status: 'healthy',
    slaTarget: 99.99,
    latencyThreshold: 120,
    pageLoadThreshold: 0.8,
    errorRateThreshold: 0.01,
    monitoringEnabled: true,
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    latestMetric: {
      id: 'm-2',
      serviceId: 'srv-2',
      latency: 42,
      pageLoadTime: 0.35,
      uptime: 100,
      errorRate: 0.0,
      timestamp: new Date().toISOString(),
    },
  },
  {
    id: 'srv-3',
    name: 'Auth0 Identity Service',
    description: 'User authentication, OAuth2 & SSO token provider',
    url: 'https://auth.slapulse.auth0.com/oauth/token',
    environment: 'Production',
    region: 'us-east-1',
    status: 'healthy',
    slaTarget: 99.99,
    latencyThreshold: 180,
    pageLoadThreshold: 1.0,
    errorRateThreshold: 0.02,
    monitoringEnabled: true,
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    latestMetric: {
      id: 'm-3',
      serviceId: 'srv-3',
      latency: 112,
      pageLoadTime: 0.62,
      uptime: 100,
      errorRate: 0.01,
      timestamp: new Date().toISOString(),
    },
  },
  {
    id: 'srv-4',
    name: 'OpenAI GPT-4 API',
    description: 'Large language model inference endpoint for AI features',
    url: 'https://api.openai.com/v1/chat/completions',
    environment: 'Production',
    region: 'us-west-2',
    status: 'degraded',
    slaTarget: 99.5,
    latencyThreshold: 1200,
    pageLoadThreshold: 3.5,
    errorRateThreshold: 0.5,
    monitoringEnabled: true,
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    latestMetric: {
      id: 'm-4',
      serviceId: 'srv-4',
      latency: 1420,
      pageLoadTime: 3.8,
      uptime: 99.2,
      errorRate: 0.45,
      timestamp: new Date().toISOString(),
    },
  },
  {
    id: 'srv-5',
    name: 'SendGrid Email Engine',
    description: 'Transactional & marketing email dispatch cluster',
    url: 'https://api.sendgrid.com/v3/mail/send',
    environment: 'Production',
    region: 'us-east-1',
    status: 'healthy',
    slaTarget: 99.9,
    latencyThreshold: 350,
    pageLoadThreshold: 1.5,
    errorRateThreshold: 0.1,
    monitoringEnabled: true,
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    latestMetric: {
      id: 'm-5',
      serviceId: 'srv-5',
      latency: 210,
      pageLoadTime: 0.95,
      uptime: 99.95,
      errorRate: 0.02,
      timestamp: new Date().toISOString(),
    },
  },
  {
    id: 'srv-6',
    name: 'Algolia Search Index',
    description: 'Ultra-low latency full-text search engine',
    url: 'https://slapulse-dsn.algolia.net/1/indexes',
    environment: 'Production',
    region: 'eu-west-1',
    status: 'healthy',
    slaTarget: 99.99,
    latencyThreshold: 80,
    pageLoadThreshold: 0.5,
    errorRateThreshold: 0.01,
    monitoringEnabled: true,
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    latestMetric: {
      id: 'm-6',
      serviceId: 'srv-6',
      latency: 28,
      pageLoadTime: 0.22,
      uptime: 100,
      errorRate: 0.0,
      timestamp: new Date().toISOString(),
    },
  },
  {
    id: 'srv-7',
    name: 'Cloudflare Edge CDN',
    description: 'Global edge content delivery & DDoS mitigation network',
    url: 'https://api.cloudflare.com/client/v4/zones',
    environment: 'Production',
    region: 'global-edge',
    status: 'healthy',
    slaTarget: 99.999,
    latencyThreshold: 45,
    pageLoadThreshold: 0.4,
    errorRateThreshold: 0.005,
    monitoringEnabled: true,
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    latestMetric: {
      id: 'm-7',
      serviceId: 'srv-7',
      latency: 18,
      pageLoadTime: 0.15,
      uptime: 100,
      errorRate: 0.0,
      timestamp: new Date().toISOString(),
    },
  },
  {
    id: 'srv-8',
    name: 'MongoDB Atlas Cluster',
    description: 'Primary NoSQL document database cluster',
    url: 'https://cloud.mongodb.com/api/atlas/v1.0',
    environment: 'Production',
    region: 'us-east-1',
    status: 'healthy',
    slaTarget: 99.95,
    latencyThreshold: 75,
    pageLoadThreshold: 0.6,
    errorRateThreshold: 0.02,
    monitoringEnabled: true,
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    latestMetric: {
      id: 'm-8',
      serviceId: 'srv-8',
      latency: 34,
      pageLoadTime: 0.28,
      uptime: 99.98,
      errorRate: 0.001,
      timestamp: new Date().toISOString(),
    },
  },
];

export const demoDashboardData: DashboardData = {
  kpis: {
    uptime: 99.98,
    uptimeSlaTarget: 99.9,
    avgLatency: 142,
    avgPageLoad: 0.88,
    slaCompliance: 98.6,
  },
  services: {
    total: 15,
    healthy: 14,
    degraded: 1,
    down: 0,
  },
  incidents: {
    total: 3,
    critical: 0,
    high: 1,
    medium: 2,
    low: 0,
  },
  unreadAlerts: 2,
  serviceHealth: demoServices.map((s) => ({
    id: s.id,
    name: s.name,
    status: s.status,
    latency: s.latestMetric?.latency || 100,
    uptime: s.latestMetric?.uptime || 99.9,
    slaTarget: s.slaTarget,
  })),
};

export const demoIncidents: Incident[] = [
  {
    id: 'inc-1',
    serviceId: 'srv-4',
    severity: 'high',
    title: 'High Latency Spike on GPT-4 Inference Endpoint',
    description: 'Response time exceeded 1200ms threshold due to upstream provider rate limits.',
    status: 'investigating',
    slaImpact: 0.08,
    notes: 'Monitoring upstream status page. Traffic partially rerouted to backup cluster.',
    startedAt: new Date(Date.now() - 45 * 60000).toISOString(),
    resolvedAt: null,
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
    service: { id: 'srv-4', name: 'OpenAI GPT-4 API' },
  },
  {
    id: 'inc-2',
    serviceId: 'srv-5',
    severity: 'medium',
    title: 'SendGrid Webhook Delay',
    description: 'Minor dispatch delay experienced during high-volume newsletter campaign.',
    status: 'resolved',
    slaImpact: 0.02,
    notes: 'Queue cleared automatically. Normal dispatch speeds restored.',
    startedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    resolvedAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
    service: { id: 'srv-5', name: 'SendGrid Email Engine' },
  },
];

export const demoAlerts: Alert[] = [
  {
    id: 'alt-1',
    serviceId: 'srv-4',
    severity: 'critical',
    message: 'OpenAI GPT-4 API latency spike: 1420ms exceeds 1200ms SLA target!',
    isRead: false,
    createdAt: new Date(Date.now() - 30 * 60000).toISOString(),
    service: { id: 'srv-4', name: 'OpenAI GPT-4 API' },
  },
  {
    id: 'alt-2',
    serviceId: 'srv-1',
    severity: 'info',
    message: 'Stripe Payment Gateway operating at 100% SLA compliance over past 24h.',
    isRead: true,
    createdAt: new Date(Date.now() - 120 * 60000).toISOString(),
    service: { id: 'srv-1', name: 'Stripe Payment Gateway' },
  },
];

export const demoSLAList: SLAStatus[] = demoServices.map((s) => ({
  serviceId: s.id,
  serviceName: s.name,
  environment: s.environment,
  region: s.region,
  slaTarget: s.slaTarget,
  currentUptime: s.latestMetric?.uptime || 99.9,
  currentLatency: s.latestMetric?.latency || 100,
  currentPageLoad: s.latestMetric?.pageLoadTime || 0.8,
  currentErrorRate: s.latestMetric?.errorRate || 0.01,
  latencyLimit: s.latencyThreshold,
  pageLoadLimit: s.pageLoadThreshold,
  errorRateLimit: s.errorRateThreshold,
  status: s.status === 'degraded' ? 'at-risk' : 'healthy',
  uptimeOk: true,
  latencyOk: s.status !== 'degraded',
  pageLoadOk: true,
  errorRateOk: true,
  lastChecked: new Date().toISOString(),
  slaConfig: s.slaConfig || null,
}));

export const generateDemoMetrics = (): Metric[] => {
  const metrics: Metric[] = [];
  const now = Date.now();
  for (let i = 24; i >= 0; i--) {
    const timestamp = new Date(now - i * 3600000).toISOString();
    demoServices.forEach((s) => {
      const baseLat = s.latestMetric?.latency || 100;
      metrics.push({
        id: `m-demo-${s.id}-${i}`,
        serviceId: s.id,
        latency: Math.round(baseLat + (Math.random() * 30 - 15)),
        pageLoadTime: +(0.5 + Math.random() * 0.4).toFixed(2),
        uptime: 100,
        errorRate: +(Math.random() * 0.02).toFixed(3),
        timestamp,
      });
    });
  }
  return metrics;
};

export const demoReport: Report = {
  period: {
    from: new Date(Date.now() - 7 * 86400000).toISOString(),
    to: new Date().toISOString(),
    range: '7d',
  },
  summary: {
    totalServices: 15,
    totalMetrics: 10080,
    totalIncidents: 3,
    resolvedIncidents: 2,
    avgLatency: 142,
    avgUptime: 99.98,
    overallSLACompliance: 98.6,
  },
  serviceReports: demoServices.map((s) => ({
    serviceId: s.id,
    serviceName: s.name,
    environment: s.environment,
    region: s.region,
    slaTarget: s.slaTarget,
    avgLatency: s.latestMetric?.latency || 120,
    avgPageLoad: s.latestMetric?.pageLoadTime || 0.8,
    avgUptime: s.latestMetric?.uptime || 99.95,
    avgErrorRate: s.latestMetric?.errorRate || 0.01,
    incidentCount: s.id === 'srv-4' ? 1 : 0,
    slaBreaches: s.id === 'srv-4' ? 1 : 0,
    slaCompliance: s.id === 'srv-4' ? 95.4 : 99.9,
  })),
};
